import { Incident } from './types';

export const mockIncidents: Incident[] = [
  {
    id: '1',
    srNo: 1,
    incidentRefNo: 'INC-2026-001',
    incidentDate: '2026-05-01',
    incidentDetails: 'Database server went down causing production outage for all users.',
    incidentCategory: 'Database',
    likelihood: 'High',
    impact: 'Very High',
    riskScore: 20,
    riskLevel: 'Critical',
    priority: 'Critical',
    rca: 'Disk space exhausted on primary DB node due to unrotated logs.',
    status: 'Resolved',
  },
  {
    id: '2',
    srNo: 2,
    incidentRefNo: 'INC-2026-002',
    incidentDate: '2026-05-05',
    incidentDetails: 'Network latency spike observed in US-East region.',
    incidentCategory: 'Network',
    likelihood: 'Medium',
    impact: 'High',
    riskScore: 12,
    riskLevel: 'High',
    priority: 'High',
    rca: 'Under investigation.',
    status: 'In Progress',
  },
  {
    id: '3',
    srNo: 3,
    incidentRefNo: 'INC-2026-003',
    incidentDate: '2026-05-10',
    incidentDetails: 'Authentication service returning 500 errors intermittently.',
    incidentCategory: 'Application',
    likelihood: 'High',
    impact: 'Medium',
    riskScore: 12,
    riskLevel: 'High',
    priority: 'High',
    rca: 'Memory leak in auth microservice identified.',
    status: 'Open',
  },
  {
    id: '4',
    srNo: 4,
    incidentRefNo: 'INC-2026-004',
    incidentDate: '2026-05-12',
    incidentDetails: 'Suspicious login attempts detected from multiple IPs.',
    incidentCategory: 'Security',
    likelihood: 'Very High',
    impact: 'High',
    riskScore: 20,
    riskLevel: 'Critical',
    priority: 'Critical',
    rca: 'Brute force attack detected. IP block applied.',
    status: 'Closed',
  },
  {
    id: '5',
    srNo: 5,
    incidentRefNo: 'INC-2026-005',
    incidentDate: '2026-05-14',
    incidentDetails: 'Scheduled backup job failed silently for 3 consecutive nights.',
    incidentCategory: 'Software',
    likelihood: 'Medium',
    impact: 'Medium',
    riskScore: 9,
    riskLevel: 'Medium',
    priority: 'Medium',
    rca: '',
    status: 'Open',
  },
];
